### ISSUE TITLE
Redmine 3.x support

### ISSUE THREAD

**Issue by atopcu** [zaneli/akayagi#5]
Hi zaneli,
I hope that you have a plan to upgrade.

Regards,
Adnan

**Comment by zaneli** [comment]
OK, I'll try it!
Please give me a little time.

**Comment by zaneli** [comment]
@atopcu 
I fixed Akayagi for Redmine 3.x.
The [version 0.0.3](https://github.com/zaneli/akayagi/releases/tag/v0.0.3) seems to work well at Redmine version 3.1.0.stable.

**Comment by atopcu** [comment]
many Thanks @zaneli.

I tested, it works perfectly.

Regards.

**Comment by zaneli** [comment]
It's my pleasure. :)
